### ISSUE TITLE
range 10-20

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1031]
## Ranges

```rust
10-20
```

## Issue

Exception while getting the trace for range 10 -> 20

java.lang.RuntimeException: RomChunk with address 0x1ac114c2099afaf5261731655dc6c306bfcd4dbd, deployment number 0 and deploymentStatus true not found
        at net.consensys.linea.zktracer.module.romlex.RomLex.getCodeFragmentIndexByMetadata(RomLex.java:99) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.fragment.account.AccountFragment.resolvePostConflation(AccountFragment.java:197) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.defer.DeferRegistry.resolvePostConflation(DeferRegistry.java:142) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceEndConflation(Hub.java:458) ~[?:?]
        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:177) ~[?:?]

**Comment by FlorianHuc** [comment]
in RomLex
`public int getCodeFragmentIndexByMetadata(final ContractMetadata metadata) `
we look for the metadata:
ContractMetadata[address=0x1ac114c2099afaf5261731655dc6c306bfcd4dbd, deploymentNumber=0, underDeployment=false]

but in the chunks we have:
ContractMetadata[address=0x1ac114c2099afaf5261731655dc6c306bfcd4dbd, deploymentNumber=0, underDeployment=true]

so it does not find it and fails with an exception.

**Comment by OlivierBBB** [comment]
> deployment number 0 and deploymentStatus true not found

With a bit of luck those issues are fixed in the latest PR that was merged today @FlorianHuc

**Comment by OlivierBBB** [comment]
This range works for me on the lates arith-dev.
