### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gusiri** [Consensys/besu-sequencer-plugins#1043]
## Ranges

```rust
5118361-5118389
5120940-5120972
5120605-5120635
5123096-5123132
5124484-5124515
```

## Issue

Tracer failed: Internal Server Error

Linea-tracer: v0.5.1-beta
Constraints: v0.5.1-beta (b6bf989)
Corset: latest (fcd3035)
Zkevm.bin: v0.5.1-beta (b6bf989) + HUB, GAS, OOB, and STP disabled
Server: first besu node: ec2-18-117-9-115.us-east-2.compute.amazonaws.com

```

Internal Server Error
real    1m50.775s
user    0m0.008s
sys     0m0.000s
[Done]  trace for range 5118361-5118389


Internal Server Error
real    3m35.272s
user    0m0.012s
sys     0m0.000s
[Done]  trace for range 5120940-5120972

Internal Server Error
real    3m35.274s
user    0m0.012s
sys     0m0.000s
[Done]  trace for range 5120605-5120635

Internal Server Error
real    5m28.097s
user    0m0.000s
sys     0m0.016s
[Done]  trace for range 5123096-5123132


Internal Server Error
real    3m13.046s
user    0m0.011s
sys     0m0.000s
[Done]  trace for range 5124484-5124515


```

**Comment by FlorianHuc** [comment]
can you add the ranges for which this happen?

**Comment by FlorianHuc** [comment]
logs for the first range: 5118361-5118389

07:33:03.621 [vert.x-worker-thread-5] ERROR net.consensys.linea.zktracer.ZkTracer - First exception that was caught while tracing:
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-33.0.0-jre.jar:?]
        at net.consensys.linea.zktracer.module.hub.Hub.exitDeploymentFromDeploymentInfoPointOfView(Hub.java:714) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceContextExit(Hub.java:662) ~[?:?]
        at net.consensys.linea.zktracer.ZkTracer.traceContextExit(ZkTracer.java:311) ~[?:?]
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:219) ~[besu-evm-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:607) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:457) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:229) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]

**Comment by gusiri** [comment]
@FlorianHuc ah, thank you so much for the logs. Tried to get those logs but it was not that easy ;)
