### ISSUE TITLE
BlockHash missing in replay File

### ISSUE THREAD

**Issue by gusiri** [Consensys/besu-sequencer-plugins#1068]
Testing block: 4315803

{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}
real    0m2.104s
user    0m0.001s
sys     0m0.004s

Testing block: 3226470

{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}
real    0m4.750s
user    0m0.005s
sys     0m0.000s

**Comment by letypequividelespoubelles** [comment]
is it in selfDestruct as in https://github.com/Consensys/linea-tracer/issues/1063 ?

**Comment by gusiri** [comment]
I see these two types of error messages. 

### type 1
12:05:37.108 [vert.x-worker-thread-13] ERROR org.hyperledger.besu.ethereum.api.query.BlockchainQueries - failed worldstate query for 0xc20ab69d5b4a8e274c197438eea45b95a560fffbc9a2f64165479e271ba5bbf6
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')
        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.getAndMapWorldState(BlockchainQueries.java:946) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$1(Tracer.java:49) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:47) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:37) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:154) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at net.consensys.linea.plugins.rpc.tracegeneration.GenerateConflatedTracesV2.execute(GenerateConflatedTracesV2.java:87) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.PluginJsonRpcMethod.response(PluginJsonRpcMethod.java:50) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210) ~[vertx-core-4.5.8.jar:4.5.8]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

-----------
### type 2
This one looks like the selfDestruct you mentioned. 

12:05:37.110 [vert.x-worker-thread-13] ERROR net.consensys.linea.zktracer.ZkTracer - First exception that was caught while tracing:
java.lang.ClassCastException: class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')
        at net.consensys.linea.zktracer.module.hub.section.halt.SelfdestructSection.<init>(SelfdestructSection.java:86) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceOpcode(Hub.java:1035) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.processStateExec(Hub.java:958) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.tracePreExecution(Hub.java:731) ~[?:?]
        at net.consensys.linea.zktracer.ZkTracer.tracePreExecution(ZkTracer.java:258) ~[?:?]
        at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:207) ~[besu-evm-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:175) ~[besu-evm-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:198) ~[besu-evm-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:607) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:457) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:229) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$6(TraceServiceImpl.java:214) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:200) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$2(TraceServiceImpl.java:164) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:162) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.getAndMapWorldState(BlockchainQueries.java:946) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$1(Tracer.java:49) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:47) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:37) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:154) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at net.consensys.linea.plugins.rpc.tracegeneration.GenerateConflatedTracesV2.execute(GenerateConflatedTracesV2.java:87) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.PluginJsonRpcMethod.response(PluginJsonRpcMethod.java:50) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210) ~[vertx-core-4.5.8.jar:4.5.8]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
12:05:39.159 [EthScheduler-Workers-0] INFO  org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask - Imported #8,932,138 / 9 tx / 0 om / 972,961 (1.6%) gas / (0xd292ba8589637d1b5969dc0c4972776007c233839840df04df53b364ae09a686) in 0.061s. Peers: 21

**Comment by letypequividelespoubelles** [comment]
block 4315803 is ok.
block 3226470 it seems a replay Test issue : here is the exception I have 
![image](https://github.com/user-attachments/assets/9f07e938-3793-46e7-b3ca-1adde63b76eb)

@DavePearce could you please have a look ? TY

**Comment by letypequividelespoubelles** [comment]
@DavePearce I already created a branch with the replay file that is failing

**Comment by letypequividelespoubelles** [comment]
ok my bad, I was using an old release to capture block TY @DavePearce
