### ISSUE TITLE
failing blocks

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#1090]
## Ranges

These are all mono block issues.

```rust
1002387-1002387
1003970-1003970
1010069-1010069
1100579-1100579
1104982-1104982
1105022-1105022
1105029-1105029
1105038-1105038
1106506-1106506
1106648-1106648
1107867-1107867
1204298-1204298
1213822-1213822
1214117-1214117
1214259-1214259
1214280-1214280
1214528-1214528
1400040-1400040
1409462-1409462
1410650-1410650
1505729-1505729
1507291-1507291
1511808-1511808
1714851-1714851
1809818-1809818
1812784-1812784
1814860-1814860
```

## Issue

These blocks are failing in the [`v0.5.2-beta`](https://github.com/Consensys/linea-tracer/releases/tag/v0.5.2-beta) release. Thank you @FlorianHuc 

  - [x] #1103
  - [x]  1003970 (non issue)
  - [x]  1010069 (non issue)
  - [x]  1100579 (non issue)
  - [ ]  1104982
  - [ ]  1105022
  - [ ]  1105029
  - [ ]  1105038
  - [ ]  1106506
  - [x]  1106648 (non issue)
  - [x]  1107867 (non issue)
  - [x]  1204298 (non issue)
  - [x]  1213822 (non issue)
  - [x]  1214117 (non issue)
  - [x]  1214259 (non issue)
  - [x]  1214280 (non issue)
  - [x]  1214528 (non issue)
  - [x]  1400040 (non issue)
  - [x]  1409462 (non issue)
  - [ ]  1410650
  - [x]  1505729 (non issue)
  - [x] #1099
  - [x]  1511808 (non issue)
  - [x]  1714851 (non issue)
  - [x]  1809818 (non issue)
  - [x]  1812784 (non issue)
  - [ ]  1814860
  - [ ]  2907106
  - [ ]  2907117
  - [ ]  2907517
  - [ ]  2907526
  - [ ]  2907599
  - [ ]  2908024
  - [ ]  2908667
  - [ ]  2912090
  - [ ]  2913605
  - [ ]  2915562
  - [ ]  2915570
  - [ ]  2917089
  - [ ]  2917640
  - [ ]  2919284
  - [ ]  2919513
  - [ ]  2920232
  - [ ]  2920240
  - [ ]  2920822
  - [ ]  2920966
  - [ ]  2921651
  - [ ]  2822241
  - [ ]  2522886
  - [ ] 8043758
  - [ ] 8005327
  - [ ] 8019521
  
Of the **27** blocks @FlorianHuc provided
- only **9** provoke an exception on my end (fresh branch created from arith-dev)
  - **8** of these fail all because of the `ReturnSection` (the usual stuff: a `Preconditions.checkArgument` that fails)
  - **1** fails for several reasons, #1099

<img width="388" alt="image" src="https://github.com/user-attachments/assets/bde871a9-1d6c-4bb0-8800-aead127ec1ca">

**Comment by letypequividelespoubelles** [comment]
for the RETURN issue, seems the same as in #1061

**Comment by FlorianHuc** [comment]
A new serie of failing blocks:

 2907106
 2907117
 2907517
 2907526
 2907599
 2908024
 2908667
 2912090
 2913605
 2915562
 2915570
 2917089
 2917640
 2919284
 2919513
 2920232
 2920240
 2920822
 2920966
 2921651
 2822241
 2522886
 
 I am adding them to the list.
 
 all seem to fail due to:
 
 java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-33.0.0-jre.jar:?]
        at net.consensys.linea.zktracer.module.hub.section.halt.ReturnSection.<init>(ReturnSection.java:153) ~[?:?]

**Comment by letypequividelespoubelles** [comment]
Yes we have an issue in the gas cost of the return. I need to sync with @OlivierBBB to be sure I understood well, and then I'll push a fix. No need to publish all blocks, they are all failing for the same reason.

**Comment by FlorianHuc** [comment]
three more blocks:


blockNumber=8043758
07:20:19.171 [vert.x-worker-thread-19] ERROR org.hyperledger.besu.ethereum.api.query.BlockchainQueries - failed worldstate query for 0x71a447a9891baead07ec1dae958a3d283a9d820ebd2421820ba567c708be4a6b
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
  - Cannot invoke "net.consensys.linea.zktracer.module.hub.AccountSnapshot.deepCopy()" because "this.selfdestructorAccountAfter" is null
  - Cannot invoke "net.consensys.linea.zktracer.module.hub.AccountSnapshot.deepCopy()" because "this.selfdestructorAccountAfter" is null

        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]




blockNumber=8019521:

7:20:14.436 [vert.x-worker-thread-7] ERROR org.hyperledger.besu.ethereum.api.query.BlockchainQueries - failed worldstate query for 0x6ffd55ddcfe84c049ff61fa1e33acf275d3eac3d17b8c1ac92b479231efa639f
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
  - Insufficient balance
                Address: 0xf2614a233c7c3e7f08b1f887ba133a13f1eb2c55
                Balance: 0x0000000000000000000000000000000000000000000000000000000000000000
                Value: 0x00000000000000000000000000000000000000000000000000e0241f2da18713

        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]




blockNumber=8005327: 

java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-33.0.0-jre.jar:?]
        at net.consensys.linea.zktracer.module.hub.Hub.exitDeploymentFromDeploymentInfoPov(Hub.java:725) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceContextExit(Hub.java:662) ~[?:?]
