### ISSUE TITLE
selfdestruct NPE

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#1104]
## Blocks

```rust
8043758
8019521
8005327
```

## Issues

              three more blocks:

blockNumber=8043758
07:20:19.171 [vert.x-worker-thread-19] ERROR org.hyperledger.besu.ethereum.api.query.BlockchainQueries - failed worldstate query for 0x71a447a9891baead07ec1dae958a3d283a9d820ebd2421820ba567c708be4a6b
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
  - Cannot invoke "net.consensys.linea.zktracer.module.hub.AccountSnapshot.deepCopy()" because "this.selfdestructorAccountAfter" is null
  - Cannot invoke "net.consensys.linea.zktracer.module.hub.AccountSnapshot.deepCopy()" because "this.selfdestructorAccountAfter" is null

        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]

blockNumber=8019521:

7:20:14.436 [vert.x-worker-thread-7] ERROR org.hyperledger.besu.ethereum.api.query.BlockchainQueries - failed worldstate query for 0x6ffd55ddcfe84c049ff61fa1e33acf275d3eac3d17b8c1ac92b479231efa639f
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
  - Insufficient balance
                Address: 0xf2614a233c7c3e7f08b1f887ba133a13f1eb2c55
                Balance: 0x0000000000000000000000000000000000000000000000000000000000000000
                Value: 0x00000000000000000000000000000000000000000000000000e0241f2da18713

        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]

blockNumber=8005327: 

java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-33.0.0-jre.jar:?]
        at net.consensys.linea.zktracer.module.hub.Hub.exitDeploymentFromDeploymentInfoPov(Hub.java:725) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceContextExit(Hub.java:662) ~[?:?]

_Originally posted by @FlorianHuc in https://github.com/Consensys/linea-tracer/issues/1090#issuecomment-2330798966_

**Comment by letypequividelespoubelles** [comment]
maybe already fixed as https://github.com/Consensys/linea-tracer/commit/a355f8cf3fedc8ba11082991baa707391caa431b has been merged after the release

**Comment by OlivierBBB** [comment]
Are these 3 individual blocks failing ? Could you put this issue in the conventional format please @letypequividelespoubelles ?

**Comment by lorenzogentile404** [comment]
`8005327` is solved. The other 2 still needs debugging.

**Comment by lorenzogentile404** [comment]
`8043758` is solved too.

**Comment by letypequividelespoubelles** [comment]
> Are these 3 individual blocks failing ? Could you put this issue in the conventional format please @letypequividelespoubelles ?

I didn't take a look, I just copy paste https://github.com/Consensys/linea-tracer/issues/1090#issuecomment-2330798966

**Comment by OlivierBBB** [comment]
Could you still put it conventional form please @letypequividelespoubelles ?
