### ISSUE TITLE
Exception in `Wcp.callGT`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#878]
Replay `5390137-5390139` is causing an exception:

```
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because the return value of "java.util.Deque.peekLast()" is null
	at net.consensys.linea.zktracer.container.stacked.set.StackedSet.add(StackedSet.java:124)
	at net.consensys.linea.zktracer.module.wcp.Wcp.callGT(Wcp.java:128)
	at net.consensys.linea.zktracer.module.wcp.Wcp.callGT(Wcp.java:133)
	at net.consensys.linea.zktracer.module.wcp.Wcp.callGT(Wcp.java:137)
	at net.consensys.linea.zktracer.module.blockdata.Blockdata.traceEndBlock(Blockdata.java:74)
	at net.consensys.linea.zktracer.module.hub.Hub.traceEndBlock(Hub.java:1217)
	at net.consensys.linea.zktracer.ZkTracer.traceEndBlock(ZkTracer.java:216)
	at net.consensys.linea.zktracer.testing.ToyExecutionEnvironment.executeFrom(ToyExecutionEnvironment.java:175)
```

This is being thrown for block `5390137`.

**Comment by DavePearce** [comment]
This is actually part of #877.
