### ISSUE TITLE
Invalid implementation of `ToyAccount.isStorageEmpty()`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#998]
_(see also #877 and #953)_

Currently, the implementation of `ToyAccount.isStorageEmpty()` is:

```java
@Override
  public boolean isStorageEmpty() {
    return false; // TODO fix NPE triggered by setting it to this.storage.isEmpty();
  }
```

This is invalid and causes problems whenever a contract creation occurs.  Instead, it should be (as the comment suggests):

```java
@Override
  public boolean isStorageEmpty() {
    return storage.isEmpty();
  }
```

**Comment by DavePearce** [comment]
Unfortunately, this is now exposing a secondary problem (similar to that seen in #900).  For example, for the block `2250197` we get this:

```
Exceptions triggered while tracing:
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  ...


java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129)
	at net.consensys.linea.zktracer.module.romlex.RomLex.resolvePostExecution(RomLex.java:243)
	at net.consensys.linea.zktracer.module.hub.defer.DeferRegistry.resolvePostExecution(DeferRegistry.java:157)
	at net.consensys.linea.zktracer.module.hub.Hub.tracePostExecution(Hub.java:772)
	at net.consensys.linea.zktracer.ZkTracer.tracePostExecution(ZkTracer.java:276)
	at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:337)
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:175)
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:198)
	... 
```
Potentially fixes in #982 might help here --- to investigate.
